development:
  channels:
    - uibcdf
    - conda-forge
    - defaults
  dependencies:
    - jupyterlab
    - numpy
    - matplotlib
    - openmm
    - nglview
    - tqdm
    - molsysmt
    - pyunitwizard

